"""物品加is_deleted欄位，軟刪除用

Revision ID: 67617b993e51
Revises: ae59659041be
Create Date: 2026-10-07 13:36:01.206455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67617b993e51'
down_revision: Union[str, Sequence[str], None] = 'ae59659041be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_deleted')
    # ### end Alembic commands ###
