"""移除stock_transactions的image_path欄位

Revision ID: a2afef3a8e0a
Revises: f2cafed27de2
Create Date: 2026-09-16 08:54:04.359948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2afef3a8e0a'
down_revision: Union[str, Sequence[str], None] = 'f2cafed27de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_transactions', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transactions', sa.Column('image_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
