"""移除stock_transaction_items的bbox和annotation_status欄位，加prediction_id

Revision ID: ae59659041be
Revises: a2afef3a8e0a
Create Date: 2026-09-18 06:15:25.500179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ae59659041be'
down_revision: Union[str, Sequence[str], None] = 'a2afef3a8e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transaction_items', sa.Column('prediction_id', sa.Integer(), nullable=True))
    op.drop_column('stock_transaction_items', 'final_bbox')
    op.drop_column('stock_transaction_items', 'annotation_status')
    op.drop_column('stock_transaction_items', 'predicted_bbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transaction_items', sa.Column('predicted_bbox', sqlite.JSON(), nullable=True))
    op.add_column('stock_transaction_items', sa.Column('annotation_status', sa.VARCHAR(length=14), nullable=False))
    op.add_column('stock_transaction_items', sa.Column('final_bbox', sqlite.JSON(), nullable=True))
    op.drop_column('stock_transaction_items', 'prediction_id')
    # ### end Alembic commands ###
