"""create items, inventory, stock_transactions tables

Revision ID: f2cafed27de2
Revises: 
Create Date: 2026-09-13 05:46:28.346824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cafed27de2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('recognition_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('in', 'out', name='transactiontype'), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('stock_transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('final_item_id', sa.Integer(), nullable=True),
    sa.Column('final_bbox', sa.JSON(), nullable=True),
    sa.Column('predicted_class', sa.String(), nullable=True),
    sa.Column('predicted_class_score', sa.Float(), nullable=True),
    sa.Column('predicted_objectness_conf', sa.Float(), nullable=True),
    sa.Column('predicted_bbox', sa.JSON(), nullable=True),
    sa.Column('source', sa.Enum('auto_detected', 'manual_add', 'manual_correct', name='source'), nullable=False),
    sa.Column('annotation_status', sa.Enum('pending_review', 'needs_bbox', 'confirmed', name='annotationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['final_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['stock_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transaction_items')
    op.drop_table('inventory')
    op.drop_table('stock_transactions')
    op.drop_table('items')
    # ### end Alembic commands ###
